include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cloud-clipboard
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Cloud Clipboard
LUCI_DEPENDS:=+cloud-clipboard
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature